spring.application.name=procesamientoia

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=alumno
spring.datasource.password=Alumno123!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

app.admin.password=admin123
app.user.password=userpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# =========================
# CONFIGURACION PROCESAMIENTO
# =========================

openai.api-key=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
openai.model=gpt-5.5

openai.url=https://api.openai.com/v1/responses

openai.intervalo-ms=1000

openai.max-reintentos=3

openai.espera-reintento-ms=2000


# =========================
# CONFIGURACION PROCESAMIENTO
# =========================

procesamiento.numero-hilos=4